version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: securestack-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: securestack  # Ensure the database is created

  api:
    build: .
    container_name: securestack-api
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/securestack?authSource=admin
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "5000:5000"  # Match .env and server.js port
    networks:
      - securestack-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: securestack-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Memory optimization
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - securestack-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: securestack-logstash
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"   # Logstash beats input
      - "9600:9600"   # Logstash monitoring API
    networks:
      - securestack-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: securestack-kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - securestack-network

volumes:
  mongo-data:
  elasticsearch-data:

networks:
  securestack-network:
    driver: bridge
