version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: securestack-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: .
    container_name: securestack-api
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/your_db_name
    ports:
      - "3000:3000"

volumes:
  mongo-data:
