version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: securestack-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: .
    container_name: securestack-api
    restart: always
    depends_on:
      - mongodb
      - elasticsearch  # Ensuring ELK services are available
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/your_db_name
      - ELASTICSEARCH_HOST=http://elasticsearch:9200  # Link API to Elasticsearch
    ports:
      - "3000:3000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: securestack-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: securestack-logstash
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"   # Logstash beats input
      - "9600:9600"   # Logstash monitoring API

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: securestack-kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  mongo-data:
  elasticsearch-data:

