name: CI/CD & Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write  # Required for CodeQL

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Scan Dependencies (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'  # Fail pipeline if issues found

      - name: Scan Dockerfile Best Practices (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0

      - name: Scan Docker Image (Grype)
        uses: anchore/scan-action@v3
        with:
          fail-build: true  # Ensure build fails on high/critical issues

      - name: Secret Scanning (TruffleHog)
  run: docker run --rm -v ${{ github.workspace }}:/src trufflesecurity/trufflehog:latest filesystem /src

        
  build-and-push:
    needs: build-and-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ngowe9/securestack-api:latest

      - name: Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ngowe9/securestack-api:latest"
          exit-code: 1
          severity: "CRITICAL,HIGH"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy API
        run: |
          echo "Add deployment steps here!"

